// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';

export function AddContact(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DownloadAndSaveFile(arg1:string,arg2:string):Promise<void>;

export function GetContacts():Promise<Array<storage.Contact>>;

export function GetCurrentRoom():Promise<string>;

export function GetMessages(arg1:string,arg2:number):Promise<Array<storage.Message>>;

export function GetMyContactJSON():Promise<string>;

export function GetMyContactLink():Promise<string>;

export function GetProfile():Promise<Record<string, any>>;

export function SendFileNative(arg1:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function SetWindowActive(arg1:boolean):Promise<void>;

export function SwitchRoom(arg1:string):Promise<void>;

export function UpdateContactNickname(arg1:string,arg2:string):Promise<void>;

export function UpdateNickname(arg1:string):Promise<void>;
