// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddContact(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddContact'](arg1, arg2, arg3);
}

export function DownloadAndSaveFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadAndSaveFile'](arg1, arg2);
}

export function GetContacts() {
  return window['go']['main']['App']['GetContacts']();
}

export function GetCurrentRoom() {
  return window['go']['main']['App']['GetCurrentRoom']();
}

export function GetMessages(arg1, arg2) {
  return window['go']['main']['App']['GetMessages'](arg1, arg2);
}

export function GetMyContactJSON() {
  return window['go']['main']['App']['GetMyContactJSON']();
}

export function GetMyContactLink() {
  return window['go']['main']['App']['GetMyContactLink']();
}

export function GetProfile() {
  return window['go']['main']['App']['GetProfile']();
}

export function SendFileNative(arg1) {
  return window['go']['main']['App']['SendFileNative'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SetWindowActive(arg1) {
  return window['go']['main']['App']['SetWindowActive'](arg1);
}

export function SwitchRoom(arg1) {
  return window['go']['main']['App']['SwitchRoom'](arg1);
}

export function UpdateContactNickname(arg1, arg2) {
  return window['go']['main']['App']['UpdateContactNickname'](arg1, arg2);
}

export function UpdateNickname(arg1) {
  return window['go']['main']['App']['UpdateNickname'](arg1);
}
